pub const DEFAULT_PAYLOAD_SIZE: usize = 56;
pub const MAX_PAYLOAD_SIZE: usize = 65_507;

pub const DEFAULT_TIMEOUT_MILLISECONDS: u64 = 2_000;
pub const DEFAULT_INTERVAL_MILLISECONDS: u64 = 1_000;

pub const DEFAULT_SWEEP_TIMEOUT_MILLISECONDS: u64 = 500;
pub const DEFAULT_SWEEP_INTERVAL_MILLISECONDS: u64 = 10;
pub const DEFAULT_SWEEP_CONCURRENCY: usize = 16;
